name: Package Database

on:
  push:
    branches: [ master ]    

env:
  VERSION_SUFFIX: 2020.1.1

jobs:
  build:
    name: Build and Push Database

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set version
      id: set-version
      run: echo "::set-env PACKAGE_VERSION=$VERSION_SUFFIX.$GITHUB_RUN_NUMBER"
    
    - name: Make package directories
      run: mkdir -p ./packagesoutput/
    
    - name: Install and build Redgate Packages
      run: |
        $LocalModules = (New-Item "$PSScriptRoot\Modules" -ItemType Directory -Force).FullName
        Write-Host "LocalModules: $LocalModules"
        $env:PSModulePath = "$LocalModules;$env:PSModulePath"
        
        Get-PackageProvider NuGet -ForceBootstrap | Out-Null
        Import-PackageProvider PowerShellGet 
        Save-Module -Name PowerShellGet -Path $LocalModules -MinimumVersion 1.6 -Force -ErrorAction SilentlyContinue

        Save-Module -Name SqlChangeAutomation -Path $LocalModules -Force -ErrorAction SilentlyContinue -AcceptLicense
        $OctopusSQLServer = ${env:OCTOPUS_SQL_SERVER}
        Write-Host "Octopus SQL Server: $OctopusSQLServer"

        $OctopusSQLServerUserName = ${env:OCTOPUS_SQL_SERVER_USERNAME}
        $OctopusSQLServerPassword = ${env:OCTOPUS_SQL_SERVER_PASSWORD}
        $OctopusSQLServerConnectionString="Server=$OctopusSQLServer;Initial Catalog=octopustridentbuild;Persist Security Info=False;User ID=$OctopusSQLServerUserName;Password=$OctopusSQLServerPassword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

        $project = "db/src"
        $validatedArtifact = $project | Invoke-DatabaseBuild -TemporaryDatabase $OctopusSQLServerConnectionString

        $PackageVersionNumber = ${env:PACKAGE_VERSION}
        Write-Host $PackageVersionNumber
        $buildArtifact = New-DatabaseBuildArtifact $validatedProject -PackageId "OctopusTrident.Redgate.Database" -PackageVersion $PackageVersionNumber
        Export-DatabaseBuildArtifact $buildArtifact -Path "./packagesoutput/" 
      shell: pwsh     
        
