name: Package Database

on:
  push:
    branches: [ master ]    

env:
  VERSION_SUFFIX: 2020.1.1

jobs:
  build:
    name: Build and Push Database

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2      
    
    - name: Install and build Redgate Packages      
      run: |
        $LocalModules = (New-Item "$PSScriptRoot\Modules" -ItemType Directory -Force).FullName
        Write-Host "LocalModules: $LocalModules"
        $env:PSModulePath = "$LocalModules;$env:PSModulePath"
        
        Get-PackageProvider NuGet -ForceBootstrap | Out-Null
        Import-PackageProvider PowerShellGet 
        Save-Module -Name PowerShellGet -Path $LocalModules -MinimumVersion 1.6 -Force -ErrorAction SilentlyContinue

        Save-Module -Name SqlChangeAutomation -Path $LocalModules -Force -ErrorAction Stop -AcceptLicense
        Import-Module SqlChangeAutomation
        
        $project = "db/src"
        $validatedProject = $project | Invoke-DatabaseBuild

        $PackageVersionNumber = "${env:VERSION_SUFFIX}.${env:GITHUB_RUN_NUMBER}"
        Write-Host $PackageVersionNumber
        $buildArtifact = New-DatabaseBuildArtifact $validatedProject -PackageId "OctopusTrident.Redgate.Database" -PackageVersion $PackageVersionNumber
        New-Item "packagesoutput" -ItemType Directory
        Export-DatabaseBuildArtifact $buildArtifact -Path "packagesoutput" 
      shell: powershell     
        
